#!/usr/bin/perl -w
#
# autor:Manuel Hevia
# description: 
#
#-------------------------------------------
use strict;

sub p1
{
  my $file_input_name = "make_output.txt";
  my $file_output_name = "abidos_files.txt";
  
  open(f_in,"< $file_input_name") or die("error open < $file_input_name");
  my @raw_data=<f_in>;
  open(f_out,"> $file_output_name") or die("error open > $file_output_name");

  printf f_out "#\n";
  printf f_out "# generated by abidos\n";
  printf f_out "# this file is for the loader of abidos processor\n";
  printf f_out "#\n";

  foreach my $l (@raw_data) {
    chomp($l);
    $_= $l;

    my @directories = ();
    if( $_ =~ /^(g++|cc)/ ) {
      if( $_ !~ /-c/ ) {
        next;
      }

#      printf f_out "#$_\n";
      #we are in a line like this:
      #g++ -Wall -c -g -I../includes trace.cpp
	    while ($_ =~ m/-I([\S]+)/g) {
	      push(@directories, $1);
	    }

      if( $_ = /[^\-]([\S]+)\.(cpp|cc)/) {
        my $str = join(':', @directories);
        print f_out "$1.$2:$str\n";
      } else {
        print f_out "#error [$l]\n";
      }
    }
  }

  close(f_in);
  close(f_out);
}

p1;
