#!/usr/bin/perl -w
#
# autor:Manuel Hevia
# description: 
#
#-------------------------------------------
use strict;

sub p1
{
  my $file_input_name = "make_out.txt";
  my $file_output_name = "abidos_files.txt";
  
  open(f_in,"< $file_input_name") or die("error open < $file_input_name");
  my @raw_data=<f_in>;
  open(f_out,"> $file_output_name") or die("error open > $file_output_name");

  printf f_out "#\n";
  printf f_out "# generated by abidos\n";
  printf f_out "# this file is for the loader of abidos processor\n";
  printf f_out "#\n";

  foreach my $l (@raw_data) {
    chomp($l);
    $_= $l;

    my @directories = ();
    if( $_ =~ /^(g++|cc)/ ) {
      if( $_ !~ /-c/ ) {
        next;
      }

#      printf f_out "#$_\n";
      #we are in a line like this:
      #g++ -Wall -c -g -I../includes trace.cpp
	    while ($_ =~ m/-I([\S]+)/g) {
	      my $d = $1;
	      if( $d =~ /\/$/) {
	        chop($d);
        }

        push(@directories, $d);
	    }

      if( $_ = /[^\-]([\S]+)\.(cpp|cc)/) {
        #../../preprocessor/ts.cpp:../../preprocessor:../includes:.
        my $file = $1.'.'.$2;
	      if ($file =~ m/([\S]+)\/([\S]+)\.(cpp|cc)/g) {
          push(@directories, $1);
          my $str = join(':', @directories);
          print f_out "$1/$2.$3:$str\n";
	      } else {
          my $str = join(':', @directories);
          print f_out "$1.$2:$str\n";
        }
      } else {
        print f_out "#no cpp file [$l]\n";
      }
    }
  }

  close(f_in);
  close(f_out);
}

p1;
